[versions]
agp = "8.2.2"
navigation-fragment = "2.7.7"
navigation-ui = "2.7.7"
legacy-support-v4 = "1.0.0"
lifecycle-livedata = "2.7.0"
lifecycle-viewmodel = "2.7.0"
recyclerview = "1.3.2"
map-kit = "4.5.1-full"
dagger = "2.48"
dagger-compiler = "2.15"
activity = "1.8.0"
[libraries]
appcompat = { module = "androidx.appcompat:appcompat", version = "1.6.1" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version = "2.1.4" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version = "3.5.1" }
ext-junit = { module = "androidx.test.ext:junit", version = "1.1.5" }
junit = { module = "junit:junit", version = "4.13.2" }
material = { module = "com.google.android.material:material", version = "1.11.0" }
navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigation-fragment" }
navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "navigation-ui" }
legacy-support-v4 = { group = "androidx.legacy", name = "legacy-support-v4", version.ref = "legacy-support-v4" }
lifecycle-livedata = { group = "androidx.lifecycle", name = "lifecycle-livedata", version.ref = "lifecycle-livedata" }
lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "lifecycle-viewmodel" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
yandex-map-kit = { module = "com.yandex.android:maps.mobile", version.ref = "map-kit" }
dagger2 = { module = "com.google.dagger:dagger", version.ref = "dagger" }
dagger-compiler = { module = 'com.google.dagger:dagger-compiler', version.ref = "dagger-compiler" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }